public class checkDatatypes {
    public void checkBoolean(){
        Boolean checkBoolean = false;
        system.debug( 'Boolean return is= '+ checkBoolean);
    }

    public void MethodInteger (){
        integer  varFirst =1;
        integer varSecond =2;
        system.debug( 'first number is ' + ' ' + varFirst + 'second number is ' + ' ' +varSecond);
    }

    public void Stringmethod(){

        String varName= 'name';
        String var2name= 'Fulya .';
        system.debug('My ' + varName + ' is '+ var2name);
    }
}