public class Collections_assignment {
    public static void listMethods(){
        list<String> listDays =new List<String>();
        listDays.add('Monday');
        listDays.add('tuesday');
        listDays.add('wednesday');
        listDays.add('friday');
        listDays.add('sat');
        listDays.add('sunday');
        Boolean containDay= listDays.contains('day');
        system.debug(containDay);
        boolean emptyDay = listDays.isEmpty();
        system.debug(emptyday);
        Integer sizeDay =listDays.size();
        system.debug(sizeDay);

        list <string> cloneDays = new List<string>();
        cloneDays =listDays
        



    }

    public static void setMethods(){

    set<string> setDays = new Set<string>();
    setDays.add
    

    


}
}