public class dog {
 public string name;
 public string colour;
 public integer age;
 public static integer count;

 public dog (){
    count++;
    age=1;
  
 }

 public string checkAge(){
    if ((age>0) && (age<=1 )){
        system.debug ('puppy dog');
        
    } else if ((age>=1) && (age<=3 )) {
        system.debug( 'young puppy');

    } 
    else if ((age>=3) && (age<=5 )) {
        system.debug('Adult dog');
        
    }
    else {
       system.debug('Old dog') ;
    }
    
        
    }
     
    public integer showDogCount(){
        publ
        

    }
    
    }



 


