public class Player {
    public void playing(){
        String player1Name= 'Fulya';
        string player2Name= ' Zeynep';
        string player3Name= 'Sevval';
        string player4Name= 'Esat';
        string player5Name=  'Esra';

        system.debug(player1Name + player2Name+ player3Name + player5Name);
        Integer plynumber = player1Name.length();
        system.debug (plynumber);

        String Cap1= player1Name.toUpperCase();
        String Cap2 =player2Name.toUpperCase();

        system.debug (Cap1);
        system.debug(Cap2);
    }
    
}