List<string > shoppingList = new List<string>();
shoppinglist.add('camera');
shoppingList.add('music');
shoppingList.add('clothes');

System.debug(shoppingList);
string item2 =shoppingList.get(2);
string item4= shoppingList.get(4);
System.debug(item2);

list<date> birthDateList = new list<date>();
date d1= date.newInstance(1990, 10, 9);
birthDateList.add(dt1);

List<integer> numbers = new List<integer>();

numbers.add(2,3,4);
System.debug(numbers);



